#PlayerAbilityLib configuration file
#
#If alwaysLogTamperWarnings is set to false, external update messages will be logged only once per game session
#Mon Oct 21 22:44:16 EDT 2024
alwaysLogTamperWarnings=true
