name: "create-release"

on:
  push:
    branches:
      - "main"

jobs:
  upload-release:
    name: "Upload release"
    runs-on: "ubuntu-latest"
    
    steps:
      - uses: ncipollo/release-action@v1.12.0
        with:
          tag: "Latest"
          name: "Commit ${{ github.sha }}"
          commit: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}